name: Import GPG Key
description: |
  Import given GPG private key with its associated email and full name.

inputs:
  gpg-key:
    description: "GPG Private Key to import"
    required: true
  gpg-email:
    description: "Email ID associated with the GPG Key"
    required: true
    default: "regolith.linux@gmail.com"
  gpg-name:
    description: "Full Name associated with the GPG Key"
    required: true
    default: "Regolith Linux"

runs:
  using: composite
  steps:
    - name: Ensure Sudo
      uses: regolith-linux/actions/ensure-sudo@enhance-build-matrix

    - name: Environment Setup
      shell: bash
      run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends gpg gpg-agent

    - name: Import GPG Key
      shell: bash
      run: |
        mkdir -p ~/.gnupg/

        export DEBEMAIL="${{ inputs.gpg-email }}"
        export DEBFULLNAME="${{ inputs.gpg-name }}"

        printf "${{ inputs.gpg-key }}" | base64 --decode > ~/.gnupg/private.key

        chown -R $(whoami) ~/.gnupg/
        chmod 600 ~/.gnupg/*
        chmod 700 ~/.gnupg
        gpg --batch --import ~/.gnupg/private.key
