name: Get Voulage
description: |
  Clone and fetch https://github.com/regolith-linux/voulage/ repository at given ref.

inputs:
  ref:
    description: "Git repository ref to checkout"
    required: false
    default: "main"

outputs:
  path:
    description: "The path voulage is cloned into"
    value: ${{ steps.voulage.outputs.path }}

runs:
  using: composite
  steps:
    - name: Ensure Sudo
      uses: regolith-linux/actions/ensure-sudo@enhance-build-matrix

    - name: Environment Setup
      shell: bash
      run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends git ca-certificates

    - name: Get Voulage
      id: voulage
      shell: bash
      env:
        VOULAGE_REF: "${{ inputs.ref }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh
