name: Build Package
description: |
  Build a package for speficied distro/codename/stage triplet. It uses package
  name, package repo, and package ref to checkout the code.

inputs:
  name:
    description: "Name of the package to build"
    required: true
  distro:
    description: "Target Distro to build the package for (debian, ubuntu)"
    required: true
  codename:
    description: "Target Codename to build the package for (e.g. focal, bullseye)"
    required: true
  stage:
    description: "Regolith release stage (e.g. unstable, testing, stable)"
    required: true
  suite:
    description: "TODO Regolith release stage (e.g. unstable, testing, stable)"
    required: true
  component:
    description: "TODO Regolith release stage (e.g. unstable, testing, stable)"
    required: true
  arch:
    description: "TODO Regolith release stage (e.g. unstable, testing, stable)"
    required: true
  gpg-key:
    description: "GPG Private Key to import"
    required: true
  gpg-email:
    description: "Email ID associated with the GPG Key"
    required: true
    default: "regolith.linux@gmail.com"
  gpg-name:
    description: "Full Name associated with the GPG Key"
    required: true
    default: "Regolith Linux"

runs:
  using: composite
  steps:
    - name: Get Voulage
      id: voulage
      uses: regolith-linux/actions/get-voulage@main

    - name: Import GPG Key
      uses: regolith-linux/actions/import-gpg@main
      with:
        gpg-key: "${{ inputs.gpg-key }}"
        gpg-email: "${{ inputs.gpg-email }}"
        gpg-name: "${{ inputs.gpg-name }}"

    - name: Environment Setup
      shell: bash
      run: apt update && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends sudo jq git devscripts wget dput diffutils

    - name: Build Package
      shell: bash
      env:
        WORKSPACE_PATH: "${{ github.workspace }}"
        ACTIONS_PATH: "${{ runner.temp }}" # TODO
        VOULAGE_PATH: "${{ steps.voulage.outputs.path }}"

        PACKAGE_NAME: "${{ inputs.name }}"
        DISTRO: "${{ inputs.distro }}"
        CODENAME: "${{ inputs.codename }}"
        STAGE: "${{ inputs.stage }}"
        SUITE: "${{ inputs.suite }}"
        COMPONENT: "${{ inputs.component }}"
        ARCH: "${{ inputs.arch }}"

        GPG_EMAIL: "${{ inputs.gpg-email }}"
        GPG_NAME: "${{ inputs.gpg-name }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh
