name: Build Matrix of Supported Distros and Codenames
description: |
  Build a matrix of currently supported distros and codenames. The list is being
  built out of `stage/unstable` folder of https://github.com/regolith-linux/voulage/.

outputs:
  includes:
    description: "List of matrix include items"
    value: ${{ steps.builder.outputs.includes }}

runs:
  using: composite
  steps:
    - name: Get Voulage
      shell: bash
      run: $GITHUB_ACTION_PATH/get-voulage.sh

    - name: Matrix Includes Builder
      id: builder
      shell: bash
      run: $GITHUB_ACTION_PATH/build-matrix.sh
